
### register by admin
POST http://localhost:8082/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJleHAiOjE3NjI4NTYyNDYsImlhdCI6MTc2Mjc2OTg0Nn0.hiekgd1jq8oU5Ij_xKAQIJN6zdfJ-dzfbvEKV9kItxM

{
  "email": "user123@example.com",
  "password": "tes",
  "username": "User dua",
  "phone": "0888xxx",
  "address": "alamat"
}


### login  admin
POST http://localhost:8082/auth/login
Content-Type: application/json

{
  "email": "admin123@gmail.com",
  "password": "admin123"
}


### admin update user
PUT http://localhost:8082/auth/update/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYyODU2MzQyLCJpYXQiOjE3NjI3Njk5NDJ9.w5RZGiQWZKlqH8UH1KIfyw94wtJlgzJdKkfqD9tiAvE
Content-Type: application/json

{
  "email": "baru@example.com",
  "password": "resetPassword",
  "username": "nama diganti admin",
  "phone": "081234567999",
  "address": "Alamat by admin"
}



### list all order
GET http://localhost:8082/admin/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDUxMDYxLCJpYXQiOjE3NjI5NjQ2NjF9.xjyUTKI-vaS3lb6bE39ZB6_kkDrz996tQXx0IKPYPuY



### update status order
PUT http://localhost:8082/admin/orders/34/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDMwNzIyLCJpYXQiOjE3NjI5NDQzMjJ9.CK812WHqD9_a5KTbkiMgNi9rmGtUTbUG32CGvL2mkkg

{
  "status": 1
}



### Get all user 
GET http://localhost:8082/admin/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDUxMDYxLCJpYXQiOjE3NjI5NjQ2NjF9.xjyUTKI-vaS3lb6bE39ZB6_kkDrz996tQXx0IKPYPuY


### Get all products admin
GET http://localhost:8082/admin/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDUxMDYxLCJpYXQiOjE3NjI5NjQ2NjF9.xjyUTKI-vaS3lb6bE39ZB6_kkDrz996tQXx0IKPYPuY




### create products
POST http://localhost:8082/admin/product-create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDUxMDYxLCJpYXQiOjE3NjI5NjQ2NjF9.xjyUTKI-vaS3lb6bE39ZB6_kkDrz996tQXx0IKPYPuY
Content-Type: application/json

{
  "name": "Choco Irish",
  "description": "Taste of non-alcoholic Irish coffee and chocolate",
  "stock": 200,
  "category_id": 3,
  "images": [
    "image.png",
    "image2.png"
  ],
  "variants": [1, 2],
  "sizes": [
    { "size_id": 1, "price": 22000 },
    { "size_id": 2, "price": 27000 }
  ]
}


### update product
PUT http://localhost:8082/admin/product/49
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDUxMDYxLCJpYXQiOjE3NjI5NjQ2NjF9.xjyUTKI-vaS3lb6bE39ZB6_kkDrz996tQXx0IKPYPuY

{
  "name": "Choco Irish hh",
  "description": "Taste of non-alcoholic Irish coffee and chocolate",
  "stock": 200,
  "category_id": 3,
  "images": [
    "image.png",
    "image2.png"
  ],
  "variants": [1, 2],
  "sizes": [
    { "size_id": 1, "price": 22000 },
    { "size_id": 2, "price": 27000 }
  ]
}


### delete product
DELETE http://localhost:8082/admin/product/51
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYzMDUxMDYxLCJpYXQiOjE3NjI5NjQ2NjF9.xjyUTKI-vaS3lb6bE39ZB6_kkDrz996tQXx0IKPYPuY



### Admin upload user profile picture
POST http://localhost:8082/admin/2/picture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYyODQ2ODQ5LCJpYXQiOjE3NjI3NjA0NDl9.k1dOLRdRz9AgdQV9_q88tIvufy4Xo3lgMb4eNU1Eg4E
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="picture"; filename="tes.jpeg"
Content-Type: image/jpeg

< /home/fiki/Gambar/img/tes.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### upload gambar products
POST http://localhost:8082/admin/product/50/pictures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzYyODQ2ODQ5LCJpYXQiOjE3NjI3NjA0NDl9.k1dOLRdRz9AgdQV9_q88tIvufy4Xo3lgMb4eNU1Eg4E
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="myproduct.png"
Content-Type: image/png

< /home/fiki/Gambar/img/tes.png
--MyBoundary--

